### ISSUE TITLE
Some missing shell scripts

### ISSUE THREAD

**Issue by fcollman** [khaledkhairy/EM_aligner#9]
I believe there are some shell scripts that are missing from either this repo, or the render repo to make this work.  For example, the renderer_api calls '/groups/flyTEM/flyTEM/render/bin/manage-stack.sh', which has sort of 2 problems.  A) that's a hardcoded path. and B) manage-stack.sh isn't a shell script in any repo.  I can see that it is likely identical to manage_stacks.sh which is part of render 
[https://github.com/saalfeldlab/render/tree/master/render-ws-java-client/src/main/scripts]

However, other scripts are also referenced, such as from append_renderer_stack.sh
[https://github.com/khaledkhairy/EM_aligner/blob/master/renderer_api/append_renderer_stack.m]
where  it references '/groups/flyTEM/flyTEM/render/pipeline/bin/run_ws_client.sh'.

What I would like to do is extend the rc parameters to include a renderbinPath, where you would find all these shell scripts, and I would like to point it to my render installation's render-ws-java-client/src/main/scripts directory.. or somewhere i've installed that.  I can make that fall back to '/groups/flyTEM/flyTEM/render/pipeline/bin/' if its left out to keep backward compatibility at Janelia, but I need those shell scripts to be put up on github (ideally in render) to make that work for everyone, otherwise I'll have to branch out and change these calls in a manner that is specific to my environment.  I'm happy to do the work and submit a pull request with the matlab modified, if either you or Eric can get the shell scripts added to render.  @trautmane @khaledkhairy

**Comment by khaledkhairy** [comment]
It makes perfect sense to extend the rc parameter. Eric, are you adding the scripts to the renderer repo? @fcollman @trautmane

**Comment by trautmane** [comment]
I have added the missing scripts to the render repo:
https://github.com/saalfeldlab/render/commit/54d43b45b10aa373254b6f9ff9fe1c34aa11849e

**Comment by khaledkhairy** [comment]
I updated all Renderer-script calls in EM_aligner/renderer_api to accept a field renderbinPath in the rc struct, with exception of the experimental point_match_gen_SIFT*.m files.

**Comment by fcollman** [comment]
This is a minor problem.. but should be resolved one way or the other.

EM_aligner refers to a manage-stack.sh, where as the script in the render
repo is manage_stacks.sh.

Either manage-stack.sh should be added to render, or EM_aligner should
refer to manage_stacks.sh, which I believe does have the same functionality
as what it seems manage-stack.sh has... it just got renamed at some point.

best,
Forrest

On Tue, Jan 17, 2017 at 12:48 PM, Eric T. Trautman <notifications@github.com
